"""
Django settings for esther project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vvbuo22bsk_k5%8@g1g6h4*mo+qgz4*k2&1e$96_xb7s3%^b@k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_FROM_EMAIL = 'Elsie Collections <jacmuhuri@gmail.com>'
# try:
#     from .email_settings import host, user, password
EMAIL_HOST = 'smtp.gmail.com' #'smtp.sendgrid.net'
EMAIL_HOST_USER = 'jacmuhuri@gmail.com'
EMAIL_HOST_PASSWORD = '0712472060'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# except:
#     pass

SITE_URL = 'http://elsiecollections.com'
if DEBUG:
    SITE_URL = 'http://127.0.0.1:8000'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'carts',
    'orders',
    'accounts',
    'marketing',
    'localflavor',

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'marketing.middleware.DisplayMarketingMessage',
]

ROOT_URLCONF = 'esther.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['C:/Users/hp/OneDrive/Desktop/DevProjects/esther/templates/products',
        'C:/Users/hp/OneDrive/Desktop/DevProjects/esther/templates/carts' 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esther.wsgi.application'
ASGI_APPLICATION = 'esther.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Esther',
        'USER': 'postgres',
        'PASSWORD': '0712472060',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MARKETING_HOURS_OFFSET = 3
MARKETING_SECONDS_OFFSET = 0
DEFAULT_TAX_RATE = 0.16

TEMPLATE_CONTEXT_PROCESSORS = [

    'django.contrib.auth.context_processors.auth',
    'django.template.context_processors.debug',
    'django.template.context_processors.i18n',
    'django.template.context_processors.media',
    'django.template.context_processors.request',
    'django.template.context_processors.static',
    'django.template.context_processors.tz',
    'django.contrib.messages.context_processors.messages'
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'static_files')
STATICFILES_DIRS= ( os.path.join(BASE_DIR, 'static'),
    )


MEDIA_URL = 'C:/Users/hp/OneDrive/Desktop/DevProjects/esther/static/media/images/'
MEDIA_ROOT =  os.path.join(BASE_DIR, 'static', 'media', 'images')
MEDIA_DIRS= ( os.path.join(BASE_DIR, 'static'),
    )





TEMPLATES_DIRS = (os.path.join(BASE_DIR, 'templates'),


    )

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


SITE_ID = 1

STRIPE_SECRET_KEY = "sk_test_we78TYt3KAJV5QRZKUIoUrQ200yE03EKyW"

STRIPE_PUBLISHABLE_KEY = "pk_test_chj7VjnDfLXS9Uzmto9avms200Yf8w2AQ3"
