# Generated by Django 3.0.3 on 2020-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200212_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='C:/Users/hp/OneDrive/Desktop/DevProjects/esther/static/media/images/products/images/'),
        ),
    ]
