# Generated by Django 3.0.3 on 2020-02-15 12:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200215_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=products.models.item_image_upload),
        ),
    ]
