# Generated by Django 3.0.3 on 2020-02-15 12:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_newarrivals_popularproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrivals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.item_image_upload),
        ),
        migrations.AddField(
            model_name='popularproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.item_image_upload),
        ),
    ]
