# Generated by Django 3.0.3 on 2020-02-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200215_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproducts',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewArrivals',
        ),
        migrations.DeleteModel(
            name='PopularProducts',
        ),
    ]
